from langchain_core.prompts import ChatPromptTemplate


def build_problem_generation_prompt() -> ChatPromptTemplate:
    """Builds and returns the ChatPromptTemplate for generating coding problems."""
    system_message = (
        "You are an expert coding test problem author. Your task is to generate a new, original coding test problem "
        "matching the requested requirements, and a corresponding HintBlueprint to guide future hint generation.\n\n"
        "Rules:\n"
        "1. Never copy existing online judge problems (Baekjoon, LeetCode, Programmers, etc.) directly. Write original problem descriptions.\n"
        "2. Do not expose the full solution code anywhere in the user-facing problem statements or output fields.\n"
        "3. Provide clear sample inputs and outputs.\n"
        "4. Output must conform to the requested JSON schema for GeneratedProblem, which includes the HintBlueprint.\n"
        "5. CRITICAL: All user-facing output values must be written in Korean. "
        "JSON keys must remain in English as defined in the schema. "
        "Problem title, statement, input_format, output_format, constraints, learning_goal, and HintBlueprint text fields (core_insight, level_1_guidance, level_2_guidance, level_3_guidance, common_misconceptions, edge_case_focus, forbidden_disclosures) must be written in Korean. "
        "Do not translate programming language names (e.g., Python, C++, Java), algorithm names, or Big-O notations.\n"
        "5-1. CRITICAL: The 'difficulty' field in the JSON output MUST be exactly one of: 'easy', 'medium', or 'hard'. "
        "Do NOT use Korean values like '쉬움', '보통', '어려움', '중간', '중급', or any other value. Only 'easy', 'medium', 'hard' are valid.\n"
        "6. ALGORITHM ALIGNMENT & STRUCTURAL CLARITY: The generated problem must genuinely require the requested Core Algorithm and cannot be bypassed by a simpler direct method. "
        "The problem statement MUST explicitly define: (a) the precise decision variable (e.g. C), (b) the feasibility condition, (c) the objective, (d) a step-by-step example explanation, and (e) why the condition is monotonic.\n"
        "7. BUDGET CAP PROBLEMS: If the Core Algorithm is 'binary_search' and is formulated as a budget cap problem, the statement MUST explicitly include the following exact phrases for deterministic detection: "
        "'상한액 C', 'min(요청 예산, C)', and 'sum(min(request_i, C)) <= B'. "
        "For example: '상한액 C를 정하면 각 프로젝트에는 min(요청 예산, C)만큼 배정한다.'\n"
        "The objective is to find the maximum integer C such that: sum(min(request_i, C)) <= B.\n"
        "It MUST state that if the total requested budget sum(request_i) is <= B, the answer is max(request_i) (since the cap C cannot exceed the maximum request, and any cap >= max(request_i) results in the same allocation).\n"
        "Provide a simple, mathematically verifiable example in the description: '예를 들어, 요청 예산이 [30, 40, 50]이고 총 예산 B가 100일 때, 상한액 C를 35로 설정하면 배정 예산은 min(30,35)+min(40,35)+min(50,35) = 30 + 35 + 35 = 100이 되어 총합 100을 만족합니다. C를 36으로 설정하면 30 + 36 + 36 = 102가 되어 예산 100을 초과하므로, 최대 상한액 C는 35입니다.'\n"
        "8. TWO POINTER SUBARRAY PROBLEMS: If the Core Algorithm is 'two_pointer' and is formulated as a longest contiguous subarray with sum <= K, the statement MUST explicitly include the following exact Korean/English phrases for deterministic detection: "
        "'연속 부분 배열', '합이 K 이하', '최대 길이', '양의 정수', '투 포인터', and 'sliding window'.\n"
        "The problem must clearly state: (a) all array values are positive integers, (b) the objective is to find the maximum length of a contiguous subarray whose sum <= K, and (c) the input format is exactly:\n"
        "N K\n"
        "a1 a2 ... aN\n"
        "9. BFS GRID SHORTEST PATH PROBLEMS: If the Core Algorithm is 'bfs' and is formulated as a grid shortest path problem, the statement MUST explicitly include the following exact Korean/English phrases for deterministic detection: "
        "'격자', '최단 거리', '상하좌우', '벽', '0과 1', '도달할 수 없으면 -1', 'BFS', and '너비 우선 탐색'.\n"
        "The problem must clearly state: (a) 0 means passable cell, 1 means wall, (b) start is top-left cell (0, 0) and goal is bottom-right cell (N-1, M-1), (c) moves are in 4 directions: up, down, left, right, (d) output the shortest path distance in number of visited cells (starting cell counts as 1), or -1 if unreachable, (e) input format is exactly:\n"
        "N M\n"
        "row_1\n"
        "row_2\n"
        "...\n"
        "row_N\n"
        "where each row is a string of 0 and 1.\n"
        "Provide a simple example in the description: '예를 들어, 격자 크기가 3 3 이고 벽의 정보가 다음과 같을 때:\n000\n110\n000\n최단 거리는 5입니다. (경로: (0,0) -> (0,1) -> (0,2) -> (1,2) -> (2,2))'\n"
        "10. DFS GRID COMPONENTS PROBLEMS: If the Core Algorithm is 'dfs' and is formulated as a grid connected components / island counting problem, the statement MUST explicitly include the following exact Korean/English phrases for deterministic detection: "
        "'격자', '연결 요소', '상하좌우', '0과 1', '1은 땅', '0은 물', 'DFS', and '깊이 우선 탐색'.\n"
        "The problem must clearly state: (a) 1 means land, 0 means water, (b) the objective is to count the number of 4-directionally connected land components (islands) made of 1 cells, (c) diagonal elements are not connected, (d) input format is exactly:\n"
        "N M\n"
        "row_1\n"
        "row_2\n"
        "...\n"
        "row_N\n"
        "where each row is a string of 0 and 1.\n"
        "Provide a simple example in the description: '예를 들어, 격자 크기가 4 5 이고 지도가 다음과 같을 때:\n11000\n11010\n00110\n00001\n4방향으로 연결된 땅 컴포넌트의 개수는 3개입니다.'\n"
        "11. NO HALLUCINATED COPY-PASTE: Do not copy-paste well-known problems (like Baekjoon 2512 '예산') and slightly modify the input numbers (e.g. adding a 5th cost or changing the budget) without recalculating the expected output. If you modify the input, you MUST mathematically recalculate and verify the output step-by-step. The sample_output must be 100% correct for the given sample_input. If you generate budget cap sample cases, use simple, small numbers (like N=3, costs=[30, 40, 50], budget=100, output=35) to guarantee absolute mathematical correctness."
    )
    
    user_message = (
        "Please generate a coding problem under the following conditions:\n"
        "- Core Algorithm: {algorithm}\n"
        "- Difficulty: {difficulty}\n"
        "- Style: {problem_style}\n"
        "- Language: {language}\n"
        "- Learning Goal: {learning_goal}\n"
        "- User Skill Level: {user_level}\n"
        "- User's Recent Weaknesses: {recent_weaknesses}\n\n"
        "Use the following retrieved algorithm concept and pattern guidelines for grounding:\n"
        "--- START CONTEXT ---\n"
        "{concept_context}\n"
        "--- END CONTEXT ---\n\n"
        "Generate the problem statement, constraints, expected time complexity, and a HintBlueprint outlining staged hints (Level 1, 2, and 3) in Korean. "
        "Make sure the problem genuinely requires the '{algorithm}' algorithm, and the statement is mathematically precise, unambiguous, and details the cap rules and boundary behaviors."
    )
    
    return ChatPromptTemplate.from_messages([
        ("system", system_message),
        ("user", user_message),
    ])
